import { AnimatePresence } from 'framer-motion';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Presence from '@/components/general/presence/Presence';

const inter = Poppins({weight:['100','200','300','400','500','600','700','800'],subsets:['latin']});

export const metadata: Metadata = {
  title: 'PulseAnime - Latest Anime, Manga & Light Novel ',
  description: 'Generated by create next app',
  icons:'./favicon_white.ico'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
				<Presence>
					{children}
				</Presence>
			</body>
    </html>
  );
}
